CREATE TABLE ehr(
    id INT NOT NULL GENERATED ALWAYS AS IDENTITY,
    uid VARCHAR(100) UNIQUE NOT NULL GENERATED ALWAYS AS (data -> 'ehr_id' ->> 'value') STORED,
    data JSONB NOT NULL,
    PRIMARY KEY(id)
);