services:
  gopenehr:
    container_name: gopenehr
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    ports:
      - "8080:8080"
      - "2345:2345" # Debugger
    env_file: ".env"

  gopenehr-db:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  migrate:
    image: migrate/migrate
    volumes:
      - ./db/migrations:/migrations
    profiles:
      - migrate